zed2_camera:
  ros__parameters:
    mode: "ULTRA" # PERFORMANCE or ULTRA or QUALITY
    unit: "MILLIMETER" # MILLIMETER or CENTIMETER or FOOT or INCH
    minimum_distance: 400.0
    max_range: 3000.0
    topic_to_publish: "/depth_map"
    orientation: "horizontal"  # horizontal or vertical

depth_subscriber:
  ros__parameters:
    topic_to_subscribe: "/point_cloud"
    max_distance: 740.0
    sensor_height: 800  # MILLIMETERS
    orientation: "horizontal"  # horizontal or vertical
